export function registerBuiltInTools({ registry }) {
  registry.register({ id: "memory.search", title: "Search memory", risk: "read", scopes: ["memory:read"], inputSchema: { type: "object", required: ["query"] }, execute: async ({ query, limit = 10 }, context) => context.memoryRepository.search(query, { limit, status: "active" }) });
  registry.register({ id: "memory.get", title: "Get memory", risk: "read", scopes: ["memory:read"], inputSchema: { type: "object", required: ["memoryId"] }, execute: async ({ memoryId }, context) => context.memoryRepository.get(memoryId) });
  registry.register({ id: "board.get_current_state", title: "Get current board", risk: "read", scopes: ["board:read"], execute: async (_, context) => context.boardStorage.readBoard() });
  registry.register({ id: "board.search", title: "Search board", risk: "read", scopes: ["board:read"], inputSchema: { type: "object", required: ["query"] }, execute: async ({ query }, context) => { const board = await context.boardStorage.readBoard(); const q = String(query).toLowerCase(); return (board.tasks || []).filter((task) => `${task.title} ${(task.nodes || []).map((node) => `${node.title} ${node.detail || ""}`).join(" ")}`.toLowerCase().includes(q)); } });
  registry.register({ id: "agent.get_current_context", title: "Get agent context", risk: "read", scopes: ["agent:read"], execute: async (_, context) => ({ accountId: context.accountId, agentId: context.agentId || "user", workspaceId: context.workspaceId || null, sessionId: context.sessionId || null }) });
  registry.register({ id: "memory.propose_upsert", title: "Propose memory", risk: "propose", scopes: ["memory:propose"], inputSchema: { type: "object", required: ["category", "subjectKey", "statement"] }, execute: async (input, context) => ({ type: "memory_upsert", proposalId: `proposal-${Date.now()}`, accountId: context.accountId, agentId: context.agentId || "user", memory: { category: input.category, subjectKey: input.subjectKey, statement: input.statement, normalizedValue: input.normalizedValue || null, status: "candidate", sourceType: "tool" } }) });
  registry.register({ id: "board.propose_change", title: "Propose board change", risk: "propose", scopes: ["board:propose"], inputSchema: { type: "object", required: ["operation", "payload"] }, execute: async (input, context) => ({ type: "board_change", proposalId: `proposal-${Date.now()}`, accountId: context.accountId, operation: input.operation, payload: input.payload, requiresApproval: true }) });
  return registry;
}
